import { File as MEGAFile } from 'megajs';
import { parseBuffer } from 'music-metadata';
import { NextRequest } from 'next/server';

export const runtime='nodejs';
export const dynamic='force-dynamic';
const MEGA_FOLDER_URL='https://mega.nz/folder/J6ZzRYoa#kQ2tDf5tNP8NMrrGm_EXow';

type MetaResult={id:string;title:string;album:string;artist:string;artists:string[];albumArtist:string;albumArtists:string[];composers:string[];genre:string[];year:number|null;track:{no?:number;of?:number}|null};
const clean=(v:unknown)=>String(v??'').replace(/\0/g,'').replace(/[\u0001-\u0008\u000b\u000c\u000e-\u001f]/g,'').replace(/\s+/g,' ').trim();
const split=(v:unknown):string[]=>Array.isArray(v)?v.flatMap(split):clean(v)?clean(v).split(/[;\n\r,]+/).map(clean).filter(Boolean):[];
const unique=(a:string[])=>Array.from(new Set(a.map(clean).filter(Boolean)));

async function findById(root:any,id:string){const q=[root];while(q.length){const f=q.shift();for(const c of Array.isArray(f?.children)?f.children:[]){const cid=String(c?.nodeId||c?.downloadId||'');if(cid===id&&!c?.directory)return c;if(c?.directory||Array.isArray(c?.children))q.push(c)}}return null}
async function readWhole(file:any){const size=Number(file?.size||0);if(!size)throw new Error('MEGA file has no readable size');const s=file.download({start:0,end:size-1,maxConnections:1,forceHttps:true});const chunks:Buffer[]=[];await new Promise<void>((res,rej)=>{s.on('data',(c:Buffer)=>chunks.push(Buffer.from(c)));s.on('end',res);s.on('error',rej)});return Buffer.concat(chunks)}

function atomHeader(b:Buffer,o:number,end:number){if(o<0||o+8>end)return null;let size=b.readUInt32BE(o);const type=b.toString('latin1',o+4,o+8);let h=8;if(size===1){if(o+16>end)return null;const n=b.readBigUInt64BE(o+8);if(n>BigInt(Number.MAX_SAFE_INTEGER))return null;size=Number(n);h=16}else if(size===0)size=end-o;if(size<h||o+size>end)return null;return {size,type,start:o,end:o+size,dataStart:o+h}}
function decodeText(b:Buffer){const vals:string[]=[];if(b.length>=2&&b[0]===0xff&&b[1]===0xfe)vals.push(b.toString('utf16le',2));if(b.length>=2&&b[0]===0xfe&&b[1]===0xff){const x=Buffer.alloc(b.length-2);for(let i=2;i+1<b.length;i+=2){x[i-2]=b[i+1];x[i-1]=b[i]}vals.push(x.toString('utf16le'))}vals.push(b.toString('utf8'));vals.push(b.toString('latin1'));return vals.map(clean).find(Boolean)||''}
function findIlst(b:Buffer){let p=0;while((p=b.indexOf(Buffer.from('ilst','latin1'),p))!==-1){const h=atomHeader(b,p-4,b.length);if(h?.type==='ilst')return {start:h.dataStart,end:h.end};p+=4}return null}
function itemValues(b:Buffer,item:any){const out:string[]=[];let p=item.dataStart;while(p<item.end){const h=atomHeader(b,p,item.end);if(!h)break;if(h.type==='data'){const s=h.dataStart+8;if(s<h.end){const v=decodeText(b.subarray(s,h.end));if(v)out.push(v)}}p=h.end}return out}
function appleTags(b:Buffer){const out={artist:[] as string[],albumArtist:[] as string[],composer:[] as string[],album:[] as string[],title:[] as string[],freeformArtist:[] as string[]};const ilst=findIlst(b);if(!ilst)return out;let p=ilst.start;while(p<ilst.end){const item=atomHeader(b,p,ilst.end);if(!item)break;if(item.type==='©ART')out.artist.push(...itemValues(b,item));else if(item.type==='aART')out.albumArtist.push(...itemValues(b,item));else if(item.type==='©wrt'||item.type==='©com')out.composer.push(...itemValues(b,item));else if(item.type==='©alb')out.album.push(...itemValues(b,item));else if(item.type==='©nam')out.title.push(...itemValues(b,item));else if(item.type==='----'){let q=item.dataStart;let name='';while(q<item.end){const h=atomHeader(b,q,item.end);if(!h)break;if(h.type==='name')name=decodeText(b.subarray(h.dataStart,h.end));if(h.type==='data'){const s=h.dataStart+8;const v=s<h.end?decodeText(b.subarray(s,h.end)):'';const k=clean(name).toUpperCase();if(v&&k.includes('ARTIST'))out.freeformArtist.push(v);if(v&&k.includes('COMPOSER'))out.composer.push(v);if(v&&k.includes('ALBUMARTIST'))out.albumArtist.push(v)}q=h.end}}p=item.end}return {artist:unique(out.artist),albumArtist:unique(out.albumArtist),composer:unique(out.composer),album:unique(out.album),title:unique(out.title),freeformArtist:unique(out.freeformArtist)}}

async function parseOne(file:any,id:string):Promise<MetaResult>{const name=String(file?.name||'track.m4a');try{const bytes=await readWhole(file);let common:any={};try{common=(await parseBuffer(bytes,{path:name}))?.common||{}}catch(e){console.warn('music-metadata failed; using direct MP4 atoms',name,e)}const a=appleTags(bytes);const artists=unique([...a.freeformArtist,...a.artist,...split(common.artists),...split(common.artist)]);const albumArtists=unique([...a.albumArtist,...split(common.albumartists),...split(common.albumartist)]);const composers=unique([...a.composer,...split(common.composer)]);const artist=artists[0]||albumArtists[0]||'';const albumArtist=albumArtists[0]||'';return {id,title:clean(common.title)||a.title[0]||'',album:clean(common.album)||a.album[0]||'',artist:artist||'Unknown Artist',artists:artists.length?artists:(artist?[artist]:[]),albumArtist,albumArtists:albumArtists.length?albumArtists:(albumArtist?[albumArtist]:[]),composers,genre:unique(split(common.genre)),year:typeof common.year==='number'?common.year:null,track:common.track||null}}catch(e){console.warn('Metadata extraction failed',name,e);return {id,title:'',album:'',artist:'',artists:[],albumArtist:'',albumArtists:[],composers:[],genre:[],year:null,track:null}}}

export async function GET(request:NextRequest){const ids=(request.nextUrl.searchParams.get('ids')||'').split(',').map(v=>v.trim()).filter(Boolean).slice(0,10);if(!ids.length)return Response.json([]);try{const root=MEGAFile.fromURL(MEGA_FOLDER_URL);await root.loadAttributes();const results:MetaResult[]=[];for(const id of ids){const file=await findById(root,id);if(file)results.push(await parseOne(file,id))}return Response.json(results,{headers:{'Cache-Control':'no-store'}})}catch(e){console.error('MEGA metadata batch error',e);return new Response(`Unable to read song metadata: ${e instanceof Error?e.message:String(e)}`,{status:502})}}
